name: QGIS ltr nightly

on: workflow_dispatch
#  schedule:
#  - cron: '2 0 * * * *'
#
  push:
    branches:
    - workflows

jobs:
  build:
    name: qgis-ltr-dev
    runs-on: windows-latest

    env:
      TEMP: c:\temp
      BASE: c:\w

    steps:
    - name: use workspace on C
      shell: cmd
      run: |
       echo on
       cd \
       if not exist %TEMP% mkdir %TEMP%
       if not exist %BASE% mkdir %BASE%
       rd %GITHUB_WORKSPACE%
       cmd /c mklink /j %GITHUB_WORKSPACE% %BASE%
       echo >%GITHUB_WORKSPACE%\foo.txt
       if not exist %BASE%\foo.txt (echo junction not active & exit /b 1)
       del %BASE%\foo.txt

    - name: keep original line endings
      run: git config --global core.autocrlf false

    - uses: actions/checkout@v2
      with:
        fetch-depth: 120

    # WDF kills MSVC batch's own detection of SDKs…
    - name: Clean WDF
      shell: cmd
      run: |
        rmdir /s /q "%ProgramFiles(x86)%\Windows Kits\10\lib\wdf"
        rmdir /s /q "%ProgramFiles(x86)%\Windows Kits\10\include\wdf"
        rmdir /s /q "%ProgramFiles(x86)%\Windows Kits\10\redist\wdf"
        rmdir /s /q "%ProgramFiles(x86)%\Windows Kits\10\Tools"

    - name: 'Install cygwin'
      shell: cmd
      run: |
         curl --output c:\setup-x86_64.exe https://cygwin.com/setup-x86_64.exe
         c:\setup-x86_64.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/temp/cygwin -P "bison,flex,poppler,doxygen,git,unzip,tar,diffutils,patch,ssh,curl,wget,flip,p7zip"

    - name: 'Building...'
      shell: cmd
      run: |
        echo on
        rmdir /s /q "c:/temp/cygwin"
        path c:\cygwin\bin;c:\cygwin\usr\bin
        cygpath -a %GITHUB_WORKSPACE%
        for /f "delims=" %%i in ('cygpath -a %GITHUB_WORKSPACE%') do set OSGEO4W_REP=%%i
        cd %GITHUB_WORKSPACE%\src\qgis-ltr-dev\osgeo4w
        bash package.sh

# vim: set nowrap :
